name: Clone and compile paho-mqtt
author: Jose Cabral
Description: "Clone paho-mqtt and build a release static library with SSL disabled"

inputs:
  git_version:
    type: string
    Decription: Version of paho-mqtt to clone
    required: True
  
  c_compiler:
    type: string
    Description: C compiler to use, passed as CMAKE_C_COMPILER to CMake
    required: True

  platform:
    type: string
    Description: The platform where this job is running. "windows-latest" or anything else are valid values
    required: True

outputs:
  mqtt-include:
    value: ${{ steps.vars.outputs.mqtt-include }}
    description: The include directory
  mqtt-lib-dir:
    value: ${{ steps.vars.outputs.mqtt-lib-dir }}
    description: The library directory
  mqtt-lib:
    value: ${{ steps.vars.outputs.mqtt-lib }}
    description: The library to link to

runs:
  using: "composite"
  steps:
    - name: Clone paho-mqtt
      shell: bash
      run: |
        git clone https://github.com/eclipse/paho.mqtt.c.git -b ${{ inputs.git_version }}
      
    - name: Build paho-mqtt
      shell: bash
      run: |
        cd paho.mqtt.c

        cmake \
        -B static \
        -DCMAKE_C_COMPILER=${{ inputs.c_compiler }} \
        -DCMAKE_BUILD_TYPE=Release \
        -DPAHO_BUILD_STATIC=ON \
        -DPAHO_BUILD_SHARED=OFF \
        -DPAHO_WITH_SSL=OFF
        
        cmake --build static --config Release

    - name: Output variables
      id: vars
      shell: bash
      run: |
        echo "mqtt-include=${{ github.workspace }}/paho.mqtt.c/src" >> "$GITHUB_OUTPUT"
        echo "mqtt-lib-dir=${{ github.workspace }}/paho.mqtt.c/static/src/${{ inputs.platform == 'windows-latest' && 'Release' || '' }}" >> "$GITHUB_OUTPUT"
        echo "mqtt-lib=${{ inputs.platform == 'windows-latest' && 'paho-mqtt3a-static.lib' || 'libpaho-mqtt3a.a' }}" >> "$GITHUB_OUTPUT"
